apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GijsvanDulmen/sample-cluster-setup.git
    targetRevision: HEAD
    path: application
  destination:
    server: https://kubernetes.default.svc
    namespace: application01